using System.Threading.Channels;
using ConsoleApp2.App;

//TODO: THINK ABOUT FileAttributes in IndexRecord

//TODO: GITIGNORE + FIX COMMANDS BY GITIGNORE

//TODO: THINK ABOUT GARBAGE COLLECTION AND DONT REMOVING BLOBS

//TODO: FIX STATUS BUG(DIRECTORIES ALWAYS UNSTAGED) 




App.Configure();
App.Run(args);
